# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               NYNE Servants' Curriculum
tagline:             'NYNE Servants Curriculum'
description:         Curriculum for (pre-) servants of the New York and New England Diocese of the Coptic Orthodox Church
url:                 
baseurl:             '/curriculum/'
paginate:            5

# Custom vars
version:             1.0.0
